[tool.ruff]
line-length = 120

[tool.pylint.FORMAT]
max-line-length=120
[tool.pylint.'MESSAGES CONTROL']
disable='''
    missing-module-docstring,
    missing-class-docstring,
    missing-function-docstring,
    trailing-newlines,
    invalid-name
'''

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "build", "dist"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]